version: "3"
services:
  flask_backend:
    build: ./backend/
    ports: 
      - "5000:5000"
    expose:
      - 5000
    volumes:
      - ./backend:/usr/backend
  react_frontend:
    build: ./frontend/
    ports:
      - "80:5173"
    volumes:
      - ./frontend:/usr/frontend
      - /usr/frontend/node_modules