const carMakesAndModels = [
    {
        "Audi": [
            "100",
            "200",
            "80",
            "90",
            "A1",
            "A2",
            "A3",
            "A4",
            "A4 Allroad",
            "A5",
            "A6",
            "A6 Allroad",
            "A7",
            "A8",
            "Cabriolet",
            "Coup\u00c3\u0192\u00c2\u00a9",
            "Q3",
            "Q5",
            "Q7",
            "QUATTRO",
            "R8",
            "RS2",
            "RS3",
            "RS4",
            "RS5",
            "RS6",
            "RS7",
            "RSQ3",
            "S1",
            "S2",
            "S3",
            "S4",
            "S5",
            "S6",
            "S7",
            "S8",
            "SQ5",
            "TT",
            "TT RS",
            "TTS",
            "V8"
        ]
    },
    {
        "BMW": [
            "114",
            "116",
            "118",
            "120",
            "123",
            "125",
            "130",
            "135",
            "1er M Coup\u00c3\u0192\u00c2\u00a9",
            "2002",
            "214 Active Tourer",
            "216",
            "216 Active Tourer",
            "216 Gran Tourer",
            "218",
            "218 Active Tourer",
            "218 Gran Tourer",
            "220",
            "220 Active Tourer",
            "220 Gran Tourer",
            "225",
            "225 Active Tourer",
            "228",
            "315",
            "316",
            "318",
            "318 Gran Turismo",
            "320",
            "320 Gran Turismo",
            "323",
            "324",
            "325",
            "325 Gran Turismo",
            "328",
            "328 Gran Turismo",
            "330",
            "330 Gran Turismo",
            "335",
            "335 Gran Turismo",
            "ActiveHybrid 3",
            "418 Gran Coup\u00c3\u0192\u00c2\u00a9",
            "420",
            "420 Gran Coup\u00c3\u0192\u00c2\u00a9",
            "425",
            "428",
            "428 Gran Coup\u00c3\u0192\u00c2\u00a9",
            "430",
            "430 Gran Coup\u00c3\u0192\u00c2\u00a9",
            "435",
            "435 Gran Coup\u00c3\u0192\u00c2\u00a9",
            "518",
            "520",
            "520 Gran Turismo",
            "523",
            "524",
            "525",
            "528",
            "530",
            "530 Gran Turismo",
            "535",
            "535 Gran Turismo",
            "540",
            "545",
            "550",
            "550 Gran Turismo",
            "ActiveHybrid 5",
            "628",
            "630",
            "633",
            "635",
            "640",
            "640 Gran Coup\u00c3\u0192\u00c2\u00a9",
            "645",
            "650",
            "650 Gran Coup\u00c3\u0192\u00c2\u00a9",
            "725",
            "728",
            "730",
            "732",
            "735",
            "740",
            "745",
            "750",
            "760",
            "ActiveHybrid 7",
            "840",
            "850",
            "i3",
            "i8",
            "M135",
            "M235",
            "M3",
            "M4",
            "M5",
            "M550",
            "M6",
            "ActiveHybrid X6",
            "X1",
            "X3",
            "X4",
            "X5",
            "X5 M",
            "X5 M50",
            "X6",
            "X6 M",
            "X6 M50",
            "Z1",
            "Z3",
            "Z3 M",
            "Z4",
            "Z4 M",
            "Z8"
        ]
    },
    {
        "Cadillac": [
            "Allante",
            "ATS",
            "BLS",
            "CTS",
            "Deville",
            "Eldorado",
            "Escalade",
            "Fleetwood",
            "Seville",
            "SRX",
            "STS",
            "XLR"
        ]
    },
    {
        "Chevrolet": [
            "2500",
            "Alero",
            "Astro",
            "Avalanche",
            "Aveo",
            "Beretta",
            "Blazer",
            "C1500",
            "Camaro",
            "Caprice",
            "Captiva",
            "Cavalier",
            "Chevelle",
            "Chevy Van",
            "Citation",
            "Colorado",
            "Corsica",
            "Cruze",
            "El Camino",
            "Epica",
            "Evanda",
            "Express",
            "G",
            "HHR",
            "Impala",
            "K1500",
            "K30",
            "Kalos",
            "Lacetti",
            "Lumina",
            "Malibu",
            "Matiz",
            "Nubira",
            "Orlando",
            "Rezzo",
            "S-10",
            "Silverado",
            "Spark",
            "SSR",
            "Suburban",
            "Tahoe",
            "Trailblazer",
            "Trans Sport",
            "Trax",
            "Venture",
            "Volt"
        ]
    },
    {
        "Dodge": [
            "Avenger",
            "Caliber",
            "Challenger",
            "Charger",
            "Dakota",
            "Demon",
            "Durango",
            "Grand Caravan",
            "Hornet",
            "Journey",
            "Magnum",
            "Neon",
            "Nitro",
            "RAM",
            "Stealth",
            "Viper"
        ]
    },
    {
        "Fiat": [
            "124",
            "126",
            "127",
            "130",
            "131",
            "500",
            "500C",
            "500L",
            "500L Living",
            "500L Trekking",
            "500X",
            "Barchetta",
            "Brava",
            "Bravo",
            "Cinquecento",
            "Coupe",
            "Croma",
            "Dino",
            "Doblo",
            "Ducato",
            "Fiorino",
            "Freemont",
            "Grande Punto",
            "Idea",
            "Linea",
            "Marea",
            "Marengo",
            "Multipla",
            "New Panda",
            "Palio",
            "Panda",
            "Punto",
            "Punto Evo",
            "Qubo",
            "Regata",
            "Ritmo",
            "Scudo",
            "Sedici",
            "Seicento",
            "Spider Europa",
            "Stilo",
            "Strada",
            "Tempra",
            "Tipo",
            "Ulysse",
            "Uno",
            "X 1\\/9"
        ]
    },
    {
        "Ford": [
            "Aerostar",
            "B-Max",
            "Bronco",
            "C-Max",
            "Capri",
            "Cougar",
            "Courier",
            "Crown",
            "Econoline",
            "Econovan",
            "EcoSport",
            "Edge",
            "Escape",
            "Escort",
            "Excursion",
            "Expedition",
            "Explorer",
            "Express",
            "F150",
            "F250",
            "F350",
            "Fairlane",
            "Falcon",
            "Fiesta",
            "Flex",
            "Focus",
            "Fusion",
            "Galaxy",
            "Granada",
            "Grand C-Max",
            "Grand Tourneo",
            "GT",
            "Ka",
            "Kuga",
            "Maverick",
            "Mercury",
            "Mondeo",
            "Mustang",
            "Orion",
            "Probe",
            "Puma",
            "Ranger",
            "Raptor",
            "S-Max",
            "Scorpio",
            "Sierra",
            "Sportka",
            "Streetka",
            "Taunus",
            "Taurus",
            "Thunderbird",
            "Tourneo",
            "Transit",
            "Transit Connect",
            "Transit Courier",
            "Transit Custom",
            "Windstar"
        ]
    },
    {
        "Honda": [
            "Accord",
            "Aerodeck",
            "Civic",
            "Concerto",
            "CR-V",
            "CR-Z",
            "CRX",
            "Element",
            "FR-V",
            "HR-V",
            "Insight",
            "Integra",
            "Jazz",
            "Legend",
            "Logo",
            "NSX",
            "Odyssey",
            "Prelude",
            "S2000",
            "Shuttle",
            "Stream"
        ]
    },
    {
        "Hyundai": [
            "Accent",
            "Atos",
            "Azera",
            "Coupe",
            "Elantra",
            "Excel",
            "Galloper",
            "Genesis",
            "Getz",
            "Grand Santa Fe",
            "Grandeur",
            "H 100",
            "H 200",
            "H-1",
            "H-1 Starex",
            "i10",
            "i20",
            "i30",
            "i40",
            "i50",
            "ix20",
            "ix35",
            "ix55",
            "Lantra",
            "Matrix",
            "Pony",
            "S-Coupe",
            "Santa Fe",
            "Santamo",
            "Sonata",
            "Terracan",
            "Trajet",
            "Tucson",
            "Veloster",
            "Veracruz",
            "XG 30",
            "XG 350"
        ]
    },
    {
        "Infiniti": [
            "EX30",
            "EX35",
            "EX37",
            "FX",
            "G35",
            "G37",
            "M30",
            "M35",
            "M37",
            "Q45",
            "Q50",
            "Q60",
            "Q70",
            "QX50",
            "QX56",
            "QX70"
        ]
    },
    {
        "Jaguar": [
            "Daimler",
            "E-Type",
            "F-Type",
            "MK II",
            "S-Type",
            "X-Type",
            "XE",
            "XF",
            "XJ",
            "XJ12",
            "XJ40",
            "XJ6",
            "XJ8",
            "XJR",
            "XJS",
            "XJSC",
            "XK",
            "XKR"
        ]
    },
    {
        "Jeep": [
            "Cherokee",
            "CJ",
            "Comanche",
            "Commander",
            "Compass",
            "Grand Cherokee",
            "Patriot",
            "Renegade",
            "Wagoneer",
            "Willys",
            "Wrangler"
        ]
    },
    {
        "Kia": [
            "Besta",
            "Borrego",
            "Carens",
            "Carnival",
            "cee'd",
            "cee'd Sportswagon",
            "Cerato",
            "Clarus",
            "Elan",
            "Joice",
            "K2500",
            "K2700",
            "Leo",
            "Magentis",
            "Mentor",
            "Mini",
            "Opirus",
            "Optima",
            "Picanto",
            "Pregio",
            "Pride",
            "pro_cee'd",
            "Retona",
            "Rio",
            "Roadster",
            "Rocsta",
            "Sephia",
            "Shuma",
            "Sorento",
            "Soul",
            "Sportage",
            "Venga"
        ]
    },
    {
        "Lancia": [
            "Beta",
            "Dedra",
            "Delta",
            "Flaminia",
            "Flavia",
            "Fulvia",
            "Gamma",
            "Kappa",
            "Lybra",
            "MUSA",
            "Phedra",
            "Prisma",
            "Stratos",
            "Thema",
            "Thesis",
            "Voyager",
            "Ypsilon",
            "Zeta"
        ]
    },
    {
        "Land Rover": [
            "Defender",
            "Discovery",
            "Discovery Sport",
            "Freelander",
            "Range Rover",
            "Range Rover Evoque",
            "Range Rover Sport",
            "Serie I",
            "Serie II",
            "Serie III"
        ]
    },
    {
        "Lexus": [
            "CT200h",
            "ES300",
            "ES330",
            "ES350",
            "GS250",
            "GS300",
            "GS350",
            "GS430",
            "GS450",
            "GS460",
            "GX470",
            "IS200",
            "IS220",
            "IS250",
            "IS300",
            "IS350",
            "ISF",
            "LS400",
            "LS430",
            "LS460",
            "LS600",
            "LX470",
            "LX570",
            "NX200",
            "NX300",
            "RCF",
            "RX300",
            "RX330",
            "RX350",
            "RX400",
            "RX450",
            "SC400",
            "SC430"
        ]
    },
    {
        "Lotus": [
            "340 R",
            "Cortina",
            "Elan",
            "Elise",
            "Elite",
            "Esprit",
            "Europa",
            "Evora",
            "Excel",
            "Exige",
            "Super Seven"
        ]
    },
    {
        "Maserati": [
            "222",
            "224",
            "228",
            "3200",
            "418",
            "420",
            "4200",
            "422",
            "424",
            "430",
            "Biturbo",
            "Ghibli",
            "GranCabrio",
            "Gransport",
            "Granturismo",
            "Indy",
            "Karif",
            "MC12",
            "Merak",
            "Quattroporte",
            "Shamal",
            "Spyder"
        ]
    },
    {
        "Mazda": [
            "121",
            "2",
            "3",
            "323",
            "5",
            "6",
            "626",
            "929",
            "B series",
            "Bongo",
            "BT-50",
            "CX-3",
            "CX-5",
            "CX-7",
            "CX-9",
            "Demio",
            "E series",
            "Millenia",
            "MPV",
            "MX-3",
            "MX-5",
            "MX-6",
            "Premacy",
            "Protege",
            "RX-6",
            "RX-7",
            "RX-8",
            "Tribute",
            "Xedos"
        ]
    },
    {
        "Nissan": [
            "100 NX",
            "200 SX",
            "240 SX",
            "280 ZX",
            "300 ZX",
            "350Z",
            "370Z",
            "Almera",
            "Almera Tino",
            "Altima",
            "Armada",
            "Bluebird",
            "Cabstar",
            "Cargo",
            "Cherry",
            "Cube",
            "e-NV200",
            "Evalia",
            "Frontier",
            "GT-R",
            "Interstar",
            "Juke",
            "King Cab",
            "Kubistar",
            "Laurel",
            "Leaf",
            "Maxima",
            "Micra",
            "Murano",
            "Navara",
            "Note",
            "NP 300",
            "NV200",
            "NV400",
            "Pathfinder",
            "Patrol",
            "PickUp",
            "Pixo",
            "Prairie",
            "Primastar",
            "Primera",
            "Pulsar",
            "Qashqai",
            "Qashqai+2",
            "Quest",
            "Sentra",
            "Serena",
            "Silvia",
            "Skyline",
            "Sunny",
            "Terrano",
            "Tiida",
            "Titan",
            "Trade",
            "Urvan",
            "Vanette",
            "X-Trail"
        ]
    },
    {
        "Porsche": [
            "356",
            "911",
            "930",
            "964",
            "991",
            "993",
            "996",
            "997",
            "912",
            "914",
            "918",
            "924",
            "928",
            "944",
            "959",
            "962",
            "968",
            "Boxster",
            "Carrera GT",
            "Cayenne",
            "Cayman",
            "Macan",
            "Panamera"
        ]
    },
    {
        "Rover": [
            "100",
            "111",
            "114",
            "115",
            "200",
            "213",
            "214",
            "216",
            "218",
            "220",
            "25",
            "400",
            "414",
            "416",
            "418",
            "420",
            "45",
            "600",
            "618",
            "620",
            "623",
            "75",
            "800",
            "820",
            "825",
            "827",
            "City Rover",
            "Metro",
            "Montego",
            "SD",
            "Streetwise"
        ]
    },
    {
        "Subaru": [
            "B9 Tribeca",
            "Baja",
            "BRZ",
            "Forester",
            "Impreza",
            "Justy",
            "Legacy",
            "Libero",
            "OUTBACK",
            "SVX",
            "Trezia",
            "Tribeca",
            "Vivio",
            "XT",
            "XV"
        ]
    },
    {
        "Tesla": [
            "Model 3",
            "Model S",
            "Model X",
            "Roadster"
        ]
    },
    {
        "Toyota": [
            "4-Runner",
            "Auris",
            "Auris Touring Sports",
            "Avalon",
            "Avensis",
            "Avensis Verso",
            "Aygo",
            "Camry",
            "Carina",
            "Celica",
            "Corolla",
            "Corolla Verso",
            "Cressida",
            "Crown",
            "Dyna",
            "FCV",
            "FJ",
            "GT86",
            "Hiace",
            "Highlander",
            "Hilux",
            "IQ",
            "Land Cruiser",
            "Lite-Ace",
            "MR 2",
            "Paseo",
            "Picnic",
            "Previa",
            "Prius",
            "Prius+",
            "Proace",
            "RAV 4",
            "Sequoia",
            "Sienna",
            "Starlet",
            "Supra",
            "Tacoma",
            "Tercel",
            "Tundra",
            "Urban Cruiser",
            "Verso",
            "Verso-S",
            "Yaris"
        ]
    },
    {
        "Volkswagen": [
            "181",
            "Amarok",
            "Beetle",
            "Bora",
            "Buggy",
            "Caddy",
            "CC",
            "Corrado",
            "Crafter",
            "Eos",
            "Fox",
            "Golf",
            "Golf Plus",
            "Golf Sportsvan",
            "Iltis",
            "Jetta",
            "Karmann Ghia",
            "K\u00c3\u0192\u00c2\u00a4fer",
            "LT",
            "Lupo",
            "New Beetle",
            "Passat",
            "Passat CC",
            "Phaeton",
            "Polo",
            "Routan",
            "Santana",
            "Scirocco",
            "Sharan",
            "T1",
            "T2",
            "T3 Caravelle",
            "T3 Multivan",
            "T3 other",
            "T3 Kombi",
            "T4 California",
            "T4 Caravelle",
            "T4 Multivan",
            "T4 other",
            "T4 Kombi",
            "T5 California",
            "T5 Caravelle",
            "T5 Multivan",
            "T5 Shuttle",
            "T5 other",
            "T5 Kombi",
            "T6 California",
            "T6 Caravelle",
            "T6 Kombi",
            "T6 Multivan",
            "T6 other",
            "Taro",
            "Tiguan",
            "Touareg",
            "Touran",
            "up!",
            "Vento",
            "XL1"
        ]
    },
    {
        "Volvo": [
            "240",
            "244",
            "245",
            "262",
            "264",
            "340",
            "360",
            "440",
            "460",
            "480",
            "740",
            "744",
            "745",
            "760",
            "780",
            "850",
            "855",
            "940",
            "944",
            "945",
            "960",
            "965",
            "Amazon",
            "C30",
            "C70",
            "Polar",
            "S40",
            "S60",
            "S70",
            "S80",
            "S90",
            "V40",
            "V40 CC",
            "V50",
            "V60",
            "V70",
            "V90",
            "XC60",
            "XC70",
            "XC90"
        ]
    }
]  // Removed some car makes for more optimized algorithm.

// Passing in a list of objects with car attributes from flask api. Get the title and if it contains certain keywords. Add the make and model to the object.
const addMakeAndModels = (carList) => {
    if (!carList) {return false}
    
    carList = carList.map((car) => {
        let newCar = {...car}

        const carTitle = car["title"]
        for (let i=0; i<carMakesAndModels.length; i++) {
            const carMakeAndModel = Object.entries(carMakesAndModels[i])[0]
            const carBrand = carMakeAndModel[0];
            const carModels = carMakeAndModel[1];

            if (carTitle.toLowerCase().includes(carBrand.toLowerCase())) {
                newCar = {...newCar, "make": carBrand.toLowerCase()}

                for (let j=0; j<carModels.length; j++) {
                    if (carTitle.toLowerCase().includes(carModels[j].toLowerCase())) {
                        newCar = {...newCar, "model": carModels[j].toLowerCase()}
                        break;
                    }
                    newCar = {...newCar, "model": "N/A"}
                }
                break;
            }
            newCar = {...newCar, "make": "N/A", "model": "N/A"}
        }

        return newCar;
    });
    return carList;
}

export default addMakeAndModels;